### ISSUE TITLE
The plugin "iProtector" don't work for me.

### ISSUE THREAD

**Issue by Meptinity** [kenygamer/pmmp-plugins#3]
hey. could you help me? I need the plugin because I want to protect my item frame images from players. Here is the problem: I have converted the plugin to a phar file, however, my server does not start. Please convert the file to a phar or try to fix it. Thank you in advance!

Server
GenisysPRO
API 3.0.1
PHP 7.0.3

**Comment by kenygamer** [comment]
@Meptinity can you please post your server console log?

**Comment by kenygamer** [comment]
@Meptinity I do not provide support to forks. Please use PocketMine-MP instead.
