### ISSUE TITLE
iProtector broken!

### ISSUE THREAD

**Issue by XDqrkneZ** [kenygamer/pmmp-plugins#7]
#### Description

i did /area flag test edit true
and it just sent me a message: Flag not found: {Flags: edit, god, tnt, touch} 
#### Versions

* PocketMine Version:
* Plugin & Version:
* Game Version: PE / Windows 10

#### Crashdump or console errors

```
```

**Comment by kenygamer** [comment]
@XDqrkneZ Sorry for the delay. I do not want to close your issue, so could you update it to follow the issue template?

**Comment by kenygamer** [comment]
Patiently awaiting your response.
