### ISSUE TITLE
KillMoney Alpha9

### ISSUE THREAD

**Issue by MSG100TC** [kenygamer/pmmp-plugins#8]
Alpha9 for kill money?

**Comment by kenygamer** [comment]
@MSG100TC Please update using  the proper issue template.

**Comment by kenygamer** [comment]
I'm not going to give an update to this repository. As an alternative, you can try to bump the API to `3.0.0-ALPHA10` on the `plugin.yml`

**Comment by kenygamer** [comment]
@MSG100TC See https://github.com/kenygamer/KillMoney
